[Journal]
Storage=volatile
RuntimeMaxUse=16M
RuntimeKeepFree=32M
RuntimeMaxFileSize=4M
MaxRetentionSec=1day
RateLimitIntervalSec=30s
RateLimitBurst=100
ForwardToSyslog=no
ForwardToKMsg=no
ForwardToConsole=no
