"""Encode the configured handoff locally, once at startup, without disk output."""

from __future__ import annotations

import base64
from io import BytesIO

from PySide6.QtCore import QBuffer, QIODevice
from PySide6.QtGui import QImage, QPainter
import segno

from .config import ConfigurationError


def repository_qr_source(repository_url: str) -> str:
    """Return an exact 208px PNG data URL with integer modules and quiet zone.

    The caller retains this immutable source across visitor resets. No image is
    regenerated by QML, and neither the URL nor visitor data is written to disk.
    """
    try:
        code = segno.make_qr(repository_url, error="m")
    except (ValueError, segno.DataOverflowError) as exc:
        raise ConfigurationError(f"repository_url cannot be encoded as a QR: {exc}") from exc
    footprint = 208
    modules = code.symbol_size(scale=1, border=4)[0]
    scale = footprint // modules
    if scale < 1:
        raise ConfigurationError("repository_url QR does not fit the 208px handoff footprint")
    encoded = BytesIO()
    code.save(encoded, kind="png", scale=scale, border=4, dark="#000000", light="#ffffff")
    symbol = QImage.fromData(encoded.getvalue(), "PNG")
    image = QImage(footprint, footprint, QImage.Format.Format_RGB32)
    image.fill(0xFFFFFFFF)
    painter = QPainter(image)
    offset = (footprint - symbol.width()) // 2
    painter.drawImage(offset, offset, symbol)
    painter.end()
    buffer = QBuffer()
    buffer.open(QIODevice.OpenModeFlag.WriteOnly)
    if not image.save(buffer, "PNG"):
        raise RuntimeError("Cannot encode the local repository QR PNG")
    return "data:image/png;base64," + base64.b64encode(bytes(buffer.data())).decode("ascii")
